[github]
username = "quhxuxm"
token = ""
proxy = "http://127.0.0.1:10080"

[projects.pas]
name = "PAS Service"
description = "PAS Service is also named as player account service"
github_repo_url = "https://github.com/igt-playcasino/pas.git"
github_branch = "6.9.0-develop"
local_repo_path = "/Users/quhao/Workspace/playcasino/pas"
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = [
    "pas-dp1",
    "pas-dp2",
]

[projects.pas.customized_properties]

[projects.rgs]
name = "RGS Platform"
description = "The core rgs platform, which is a tomcat application."
github_repo_url = "https://github.com/igt-playcasino/rgs.git"
github_branch = "wangnile-rgs"
local_repo_path = "/Users/quhao/Workspace/playcasino/rgs"
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = [
    "rgs-dp1",
    "rgs-dp2",
]

[projects.rgs.customized_properties]

[projects.cpt]
name = "Competition Service"
description = "Competition Service is one of the promotion service to make competitions."
github_repo_url = "https://github.com/igt-playcasino/competition.git"
github_branch = "6.9.0-PR-4343"
local_repo_path = "/Users/quhao/Workspace/playcasino/competition"
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = [
    "cpt-dp1",
    "cpt-dp2",
]

[projects.cpt.customized_properties]
"com.igt.cpt.key2" = "value2"
2 = "2"
1 = "1"
3 = "4"
"Com.igt.cpt.key4" = "Value4"
"com.igt.cpt.key3" = "value3"
4 = "4"

[projects.nss]
name = "NSS Service"
description = "NSS Service is also named as native system service"
github_repo_url = "https://github.com/igt-playcasino/nss.git"
github_branch = "hailin/RGS-33207"
local_repo_path = "/Users/quhao/Workspace/playcasino/nss"
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = [
    "nss-dp1",
    "nss-dp2",
]

[projects.nss.customized_properties]
