[github]
username = "quhxuxm"
token = ""
proxy = "http://127.0.0.1:10080"

[projects.gles]
name = "GLE 4.0 Service"
description = "The GLE 4.0 service."
remote_repo_url = "https://github.com/igt-playcasino/gles.git"
working_branch = "6.10.0-develop"
available_branches = ["6.10.0-develop", "6.9.0-develop", "6.9.0-release"]
local_repo_path = 'D:\Workspace\GitHub\playcasino\gles'
build_command = "mvn clean package -DskipTests"
customized_build_command = 'mvn clean package -DskipTests -f gles\pom.xml'
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.gles.customized_properties]

[projects.gls]
name = "GLE Service"
description = "The GLE service."
remote_repo_url = "https://github.com/igt-playcasino/gls.git"
working_branch = "6.10.0-develop"
available_branches = []
local_repo_path = 'D:\Workspace\GitHub\playcasino\gls'
build_command = "mvn clean package -DskipTests"
customized_build_command = 'mvn clean package -DskipTests -f gls\pom.xml'
run_command = "mvn clean pacage -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.gls.customized_properties]

[projects.ruleengine]
name = "Rule Engine Service"
description = "The Rule Engine service."
remote_repo_url = "https://github.com/igt-playcasino/ruleengine.git"
working_branch = "6.10.0-develop"
available_branches = []
local_repo_path = 'D:\Workspace\GitHub\playcasino\ruleengine'
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.ruleengine.customized_properties]

[projects.pas]
name = "PAS Service"
description = "PAS Service is also named as player account service"
remote_repo_url = "https://github.com/igt-playcasino/pas.git"
working_branch = "6.10.0-develop"
available_branches = []
local_repo_path = 'D:\Workspace\GitHub\playcasino\pas'
build_command = "mvn clean package -DskipTests"
customized_build_command = 'mvn clean package -DskipTests -f app\pom.xml'
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.pas.customized_properties]

[projects.nss]
name = "NSS Service"
description = "NSS Service is also named as native system service"
remote_repo_url = "https://github.com/igt-playcasino/nss.git"
working_branch = "6.10.0-develop"
available_branches = []
local_repo_path = 'D:\Workspace\GitHub\playcasino\nss'
build_command = "mvn clean package -DskipTests"
customized_build_command = 'mvn clean package -DskipTests -f nss\pom.xml'
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.nss.customized_properties]

[projects.gsr]
name = "Game Service Router"
description = "The core game service router."
remote_repo_url = "https://github.com/igt-playcasino/gsr.git"
working_branch = "6.10.0-develop"
available_branches = []
local_repo_path = 'D:\Workspace\GitHub\playcasino\gsr'
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.gsr.customized_properties]
"gsr-business.bis.cptWidgetEnabled" = "N"
"gsr-business.bis.supportWidget" = "N"
"spring.datasource.url" = "jdbc:postgresql://rno-pg-db01.lab.wagerworks.com:5432/gsrdev?stringtype=unspecified"
"spring.kafka.consumer.group-id" = "GSR-${ENV_NAME:zhangsan777}"
"gsr-service-connector.cache-service.networkConfig.addresses" = "127.0.0.1:${MY_HAZELCAST_PORT}"
"spring.kafka.bootstrap-servers" = "${MY_KAFKA:localhost}:9092"
"spring.datasource.password" = "gsrdev17"
"gsr-service-connector.rgs-service.baseUrl" = "http://${MY_DOMAIN:localhost}:10580"
"gsr-service-connector.rgs-service.rgsPlatformSessionId" = "IGTRGSID"
"logging.level.root" = "ERROR"
"gsr-hazelcast-session.hazelcastMemberList" = "127.0.0.1"
"gsr-business.rgs-loadbalancer-url" = "http://${MY_DOMAIN:localhost}:10180"
"server.port" = "10280"
"gsr-service-connector.apache-service.baseUrl" = "http://${MY_DOMAIN:localhost}:10180"
"gsr-service-connector.pas-service.baseUrl" = "http://${MY_DOMAIN:localhost}:11080/pas"
"gsr-service-connector.GeoServiceStub.geoService.baseUrls" = "http://geo-pa02.lab.wagerworks.com/geoservice/api/"
"gsr-service-connector.jrs-service.baseUrl" = "http://${MY_DOMAIN:localhost}:12880/jrs"
"gsr-service-connector.competition-service.baseUrl" = "http://${MY_DOMAIN:localhost}:11280/competition"
"gsr-service-connector.nss-service.baseUrl" = "http://${MY_DOMAIN:localhost}:10980/nss"
"gsr-business.data-center-id" = "ZS"
APP_NAME = "gsr"
"gsr-service-connector.gls-service.baseUrl" = "http://${MY_DOMAIN:localhost}:12680/gls"
"gsr-service-connector.cache-service.clusterName" = "cache_${ENV_NAME}"
"jackpot.meter-host" = "jps-dev08-meter.lab.wagerworks.com"
"gsr-hazelcast-session.jvmRoute" = "gsr01"
"spring.datasource.username" = "gsrdev17"
"gsr-service-connector.cfgs-service.baseUrl" = "http://${MY_DOMAIN:localhost}:10880/cfgs"
"gsr-service-connector.GeoServiceStub.geoService.password" = "geo"
"gsr-service-connector.bis-service.baseUrl" = "http://${MY_DOMAIN:localhost}:14080/nss"
"gsr-business.flightdeck-url" = "http://${MY_DOMAIN:localhost}:11780/flightdeck/gs/flightdeck"
"gsr-service-connector.GeoServiceStub.geoService.userName" = "geo"
"gsr-service-connector.ccs-service.baseUrl" = "https://jps-dev13-meter.lab.wagerworks.com/ccs"
"gsr-service-connector.apache-service.skbIndexTplFilePath" = "/skb/gateway/$skbVersion$/index.tpl"
"gsr-business.skb-forceGetParamNames" = "landing,separatergs"
"tomcat.jvmRoute" = "gsr01"
"spring.quartz.auto-startup" = "false"
"quartz.enabled" = "false"

[projects.cache]
name = "Cache Service"
description = "The cache service."
remote_repo_url = "https://github.com/igt-playcasino/cache.git"
working_branch = "6.10.0-develop"
available_branches = ["6.10.0-develop", "6.9.0-develop", "6.9.0-release"]
local_repo_path = 'D:\Workspace\GitHub\playcasino\cache'
build_command = "mvn clean package -DskipTests"
customized_build_command = 'mvn clean package -DskipTests -f cache\pom.xml'
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.cache.customized_properties]
CACHE_HAZELCAST_QUORUM_ENABLED = "false"
"cache-service.mainHazelcastConfigurationProperties.hz.network.port" = "10701"
"gsr.db.user" = "gsrdev17"
"cache-service.mainHazelcastConfigurationProperties.hz.cluster.name" = "cache_local"
"cec.db.jdbcUrl" = "jdbc:postgresql://rno-pg-db01.lab.wagerworks.com:5432/cecdev?stringtype=unspecified"
"gsr.db.jdbcUrl" = "jdbc:postgresql://rno-pg-db01.lab.wagerworks.com:5432/gsrdev?stringtype=unspecified"
CACHE_HAZELCAST_QUORUM_SIZE = "2"
"logging.pattern.console" = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%t] [%c{1}] %msg%n"
"logging.pattern.file" = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%t] [%c{1}] %msg%n"
"gsr.db.password" = "gsrdev17"
"logging.level.root" = "DEBUG"
"cec.db.user" = "cecdev17"
"competition.datasource.url" = "jdbc:postgresql://rno-pg-db01.lab.wagerworks.com:5432/cptdev?stringtype=unspecified"
"competition.datasource.password" = "cptdev17"
"cec.db.password" = "cecdev17"
"competition.datasource.username" = "cptdev17"

[projects.cpt]
name = "Competition Service"
description = "Competition Service is one of the promotion service to make competitions."
remote_repo_url = "https://github.com/igt-playcasino/competition.git"
working_branch = "6.10.0-develop"
available_branches = [
    "6.10.0-develop",
    "6.9.0-PR-4343",
    "6.9.0-PR-4355",
    "6.9.0-RGSHOTFIX-184",
    "6.9.0-develop",
    "6.9.0-release",
    "RGS-31868---UTs-for-Competition-service",
    "RGS-31868---UTs-for-Competition-service-common-PR",
    "jeffer-cpt-6.9.0-PR4355",
    "lilin/6.9.0-PR-4355-DB",
    "lizhaowei/6.9.0-RGSHOTFIX-184",
    "lizhaowei/6.9.0-release",
    "wangnile/cpt-610",
]
local_repo_path = 'D:\Workspace\GitHub\playcasino\competition'
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.cpt.customized_properties]
"com.igt.cpt.key2" = "value2"
"Com.igt.cpt.key4" = "Value4"
"com.igt.cpt.key3" = "value3"

[projects.rgs]
name = "RGS Platform"
description = "The core rgs platform, which is a tomcat application."
remote_repo_url = "https://github.com/igt-playcasino/rgs.git"
working_branch = "6.10.0-develop"
available_branches = [
    "6.10.0-develop",
    "6.9.0-develop",
    "6.9.0-release",
    "add-deploy",
    "wangnile-rgs",
]
local_repo_path = 'D:\Workspace\GitHub\playcasino\rgs'
build_command = "mvn clean package -DskipTests"
customized_build_command = 'mvn -Dcom.sun.xml.namespace.QName.useCompatibleSerialVersionUID=1.0 -DskipTests=true -f rgs\pom.xml -P unfilter,unfilterPf,local,demo clean install'
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.rgs.customized_properties]
"hazelcast.client.clusterName" = "cache_zhangsan777"
"datagrid.hazelcast.tcp-ip.member-list" = "localhost:5757"
"datagrid.hazelcast.multicast.port" = "54326"
"jpkmeter.port" = "443"
"rgs.loadbalancer.url" = "http://localhost:10180"
"gsr.http.protocol" = "JSON"
"environment.datacenterid" = "ZS"
"datagrid.hazelcast.interfaces" = "localhost"
"jpk.host" = "jps-dev08-pool.lab.wagerworks.com"
"hazelcast.client.networkConfig.addresses" = "localhost:10701"
"gls.http.targetUrl" = "http://localhost:12680/gls"
"customplugins.dir" = "D:/rgs/rgs680/rgs/rgs_home/plugins"
"jrs.http.targetUrl" = "http://localhost:12880/jrs"
"datagrid.hazelcast.cluster.name" = "zhangsan_rgs80"
"gls.http.timeout" = "600000"
"jpk.sslindicator" = "OFF"
"gsr.http.timeout" = "1800000"
"gls.outcome.cache.enabled" = "true"
"jpk.port" = "80"
"environment.name" = "zhangsan777"
ENV_NAME = "zhangsan"
"jpkmeter.host" = "jps-dev08-meter.lab.wagerworks.com"
"kafka.broker.list" = "localhost:9092"
"rgsConfiguration.refresh.enable" = "true"
"jpk.jpsintegrationenabled" = "Y"
"datagrid.hazelcast.gamelist-map.ttl-seconds" = "3600"
"gsr.http.targetUrl" = "http://localhost:10280/gsr/flow"
"jpkmeter.sslindicator" = "ON"

[projects.jrs]
name = "Jurisdiction Service"
description = "The Jurisdiction service."
remote_repo_url = "https://github.com/igt-playcasino/jrs.git"
working_branch = "6.10.0-develop"
available_branches = []
local_repo_path = 'D:\Workspace\GitHub\playcasino\jrs'
build_command = "mvn clean package -DskipTests"
customized_build_command = "mvn clean package -DskipTests -f jrs/pom.xml"
run_command = "mvn clean package -DskipTests"
customized_run_command = "mvn clean package -DskipTests"
debug_command = "mvn clean package -DskipTests"
customized_debug_command = "mvn clean package -DskipTests"
stop_command = "mvn clean package -DskipTests"
startup_dependencies = []

[projects.jrs.customized_properties]
